name: Testing on main branch

on:
  push:
    branches:
      - main*

jobs:
  run-test:
    if: "contains(github.event.head_commit.message, 'fix ')"

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        ports:
          - 3306:3306

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs

      - name: Clear configurations
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache && chmod -R 755 "storage/framework/sessions"

      - name: Migrate databases production
        run: php artisan migrate:fresh --seed

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --parallel --verbose
